name: llm-rankers
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.9
  - transformers=4.31.0
  - nmslib
  - faiss-gpu
  - pip:
      - torch==2.0.1
      - pyserini==0.21.0
      - ir-datasets==0.5.6
      - openai==0.27.10
      - tiktoken==0.4.0
      - accelerate==0.22.0
      - numpy==1.26.4
