#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=setwise_optimized
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=23:59:00
#SBATCH --output=slurm_insertion_flan_%A.out

export PYSERINI_CACHE=$TMPDIR
export IR_DATASETS_HOME=$TMPDIR/ir_datasets/
export IR_DATASETS_TMP=$TMPDIR/tmp/ir_datasets/
module purge
module load 2023
module load Java/17.0.6
module load Anaconda3/2023.07-2

cd $HOME/llm-rankers
source activate llm-rankers
srun ./run_experiments_insertion_flan.sh
